language: ruby
gemfile:
- Gemfile
rvm:
- 2.3.0
before_script:
- cp config/database.yml.example config/database.yml
script:
- bundle exec rspec spec
bundler_args: --jobs=3 --retry=3 --without development
sudo: false
cache: bundler
notifications:
  email: false
