platform_name: Test

locales: { 'de': 'Deutsch', 'en': 'English' }

secret_key: "this_doesnt_matter_for_test_environments"

mail:
  from: test@test.fake

tracking:

mapview:
  default_latitude: 0
  default_longitude: 0

  mapbox:
    project_id: 0
    key: 0
