platform_name: Test

locales: { 'de': 'Deutsch', 'en': 'English' }

secret_key: "this_doesnt_matter_for_test_environments"

mail:
  from: 'me@localhost'

  default_url_options:
    host: "www.example.com"
    port: 80
    protocol: "http"

user_proximity: 10

tracking:

mapview:
  default_latitude: 0
  default_longitude: 0
  default_zoom: 10

  mapbox:
    project_id: 0
    key: 0

notification_emails:
  new_unapproved_project: "new.unapproved.project@example.com"
  new_abuse_report: "new.abuse.report@example.com"
